// app/layout.js
import "./globals.css";
import Navbar from "../component/Navbar";
import Footer from "../component/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <hr className="text-white"></hr>
        <Footer />
      </body>
    </html>
  );
}
